'use strict';
// The workout engine remains local-first. Each signed-in owner gets a separate,
// atomic envelope: payload + dirty flag + revision + idempotency key.
const cloud = {client:null,user:null,box:null,busy:false,timer:null,status:'local',conflict:null,recovery:false,blocked:false,authBusy:false,coachingBusy:false,coachingSynced:false};
const guestAction=action;
action=function(value){if(value==='reset'&&cloud.user){confirmDialog('Effacer le carnet de ce compte ?', 'Le carnet vide sera synchronisé sur tes appareils. Exporte tes données avant de continuer.',()=>{state=blankAccount();save();navigate('home')},'Effacer le carnet');return}guestAction(value)};
const guestSave=save, oldSettings=settingsView, oldHome=homeView, oldRender=render;
const LAST_ACCOUNT='muscu-coach-last-account';
const accountKey=id=>'muscu-coach-account-v1:'+id;
const blankAccount=()=>({...clone(BASELINE),profile:{name:'Athlète',weight:70,week:0},tests:[],workLoads:{}});
const freshBox=()=>({state:blankAccount(),revision:0,dirty:false,mutation:crypto.randomUUID(),lastSync:null});
const labels={local:'Sur cet appareil',connecting:'Connexion en cours',ready:'Compte connecté',syncing:'Synchronisation…',synced:'Sauvegardé en ligne',pending:'Modifications à envoyer',offline:'Hors connexion · conservé ici',error:'Sauvegarde en ligne indisponible',conflict:'Deux versions à départager',storage:'Stockage local indisponible'};
function bindCoachRelational(){if(!window.MuscuCoachStorage)return false;if(cloud.client&&cloud.user?.id)return window.MuscuCoachStorage.bindSupabase(cloud.client,cloud.user.id);window.MuscuCoachStorage.unbindSupabase();return false}
async function syncCoachRelational(force=false){if(!window.MuscuCoachStorage||!cloud.client||!cloud.user||!cloud.box||cloud.blocked||cloud.coachingBusy||!navigator.onLine)return {status:'skipped'};if(cloud.coachingSynced&&!force)return {status:'already_synced'};cloud.coachingBusy=true;try{bindCoachRelational();const result=await window.MuscuCoachStorage.reconcileNotebookWithSupabase(state);cloud.coachingSynced=result.status!=='partial';if(result.changed){state.coaching=window.MuscuCoachDomain.normalizeCoachingState(state.coaching);save();render()}return result}catch(error){console.warn('Synchronisation relationnelle coaching impossible',error);cloud.coachingSynced=false;return {status:'error',error}}finally{cloud.coachingBusy=false}}
function cloudStatus(s){cloud.status=s;document.querySelectorAll('[data-cloud-status]').forEach(el=>{el.textContent=labels[s];el.className='cloud-status '+s});}
function storeBox(){try{localStorage.setItem(accountKey(cloud.user.id),JSON.stringify(cloud.box));storageError=false;return true}catch{storageError=true;cloudStatus('storage');toast('Stockage plein ou indisponible. Exporte ton carnet.');return false}}
save=function(){if(cloud.blocked)return false;if(!cloud.user)return guestSave();state.savedAt=new Date().toISOString();cloud.box.state=clone(state);cloud.box.dirty=true;cloud.box.mutation=crypto.randomUUID();const ok=storeBox();cloudStatus(cloud.conflict?'conflict':navigator.onLine?'pending':'offline');scheduleSync();return ok;};
function scheduleSync(){clearTimeout(cloud.timer);cloud.timer=setTimeout(syncCloud,1000)}
function cloudCard(){const online=!!cloud.client;return `<section class="card cloud-card"><span data-cloud-status class="cloud-status ${cloud.status}">${labels[cloud.status]}</span><h2>${cloud.user?'Ta progression te suit.':'Un compte. Tous tes progrès.'}</h2><p class="small muted cloud-email">${cloud.user?esc(cloud.user.email):online?'Connecte-toi pour retrouver ton carnet sur tes appareils. Le mode local reste disponible.':'La connexion sera disponible une fois la sauvegarde en ligne activée. Ton carnet reste enregistré sur cet appareil.'}</p>${cloud.user?`<div class="row wrap"><button class="btn btn-primary" data-cloud="sync">${cloud.conflict?'Comparer les versions':'Synchroniser'}</button><button class="btn btn-outline" data-cloud="migrate">Récupérer mon ancien carnet</button><button class="btn btn-outline" data-cloud="logout">Me déconnecter</button></div><p class="micro muted" style="margin-top:16px">${cloud.box.lastSync?'Dernière synchronisation : '+esc(new Date(cloud.box.lastSync).toLocaleString('fr-FR')):'Aucune sauvegarde en ligne confirmée pour ce carnet.'} Les changements hors connexion seront envoyés au retour du réseau.</p>`:online?'<div class="row wrap"><button class="btn btn-primary" data-cloud="login">Me connecter</button><button class="btn btn-outline" data-cloud="signup">Créer mon compte</button></div>':''}<p class="micro muted" style="margin-top:14px">Sur iPhone : Partager → Sur l’écran d’accueil pour installer l’app. Ouvre-la une première fois avec du réseau avant de l’utiliser hors connexion.</p></section>`}
settingsView=function(){return cloudCard()+oldSettings().replace('La sauvegarde reste dans ce navigateur. Pour changer d’appareil ou de fichier, exporte puis importe ton carnet.','Une copie exportée reste utile. Le statut ci-dessus indique si ton carnet a été sauvegardé en ligne.').replace('3.1 ·','4.0 ·')};
homeView=function(){return `<button class="cloud-banner" data-cloud="account"><span data-cloud-status class="cloud-status ${cloud.status}">${labels[cloud.status]}</span> <span style="float:right">Mon compte →</span></button>`+oldHome()};
render=function(){oldRender();};
function loadBox(id){const raw=localStorage.getItem(accountKey(id));if(!raw)return freshBox();const b=JSON.parse(raw);b.state=normalise(b.state);if(!Number.isSafeInteger(b.revision)||b.revision<0||typeof b.mutation!=='string')throw Error('Invalid account cache');return b;}
function shield(title,message,reload=false){cloud.blocked=true;let el=document.getElementById('cloudShield');if(!el){el=document.createElement('div');el.id='cloudShield';el.className='cloud-shield';document.body.append(el)}el.innerHTML=`<div><span class="cloud-status">Muscu Coach</span><h2>${esc(title)}</h2><p>${esc(message)}</p>${reload?'<button class="btn btn-primary">Recharger</button>':''}</div>`;if(reload)el.querySelector('button').onclick=()=>location.reload();}
function unshield(){cloud.blocked=false;document.getElementById('cloudShield')?.remove()}
function applyBox(){state=clone(cloud.box.state);previewWeek=state.profile.week??0;releaseWake();closeModal();render();}
function attachSession(session){const user=session?.user||null;if(user?.id===cloud.user?.id){bindCoachRelational();return}if(cloud.box&&cloud.user)storeBox();clearTimeout(cloud.timer);cloud.conflict=null;cloud.user=user;cloud.box=null;cloud.coachingSynced=false;closeModal();if(user){try{cloud.box=loadBox(user.id);localStorage.setItem(LAST_ACCOUNT,JSON.stringify({id:user.id,email:user.email}));bindCoachRelational();applyBox();cloudStatus(navigator.onLine?'ready':'offline');scheduleSync()}catch{cloud.cacheError=true;shield('Carnet local à préserver.','La copie de ce compte ne peut pas être lue. Ne nettoie pas les données du navigateur ; contacte le support avant de la remplacer.');return}}else{bindCoachRelational();localStorage.removeItem(LAST_ACCOUNT);state=loadState();previewWeek=state.profile.week??0;releaseWake();cloudStatus('local');render()}}
async function fetchRemote(){const {data,error}=await cloud.client.from('coach_notebooks').select('payload,revision,mutation_id,updated_at').eq('user_id',cloud.user.id).maybeSingle();if(error)throw error;if(data)data.payload=normalise(data.payload);return data;}
async function syncCloud(){if(!cloud.client||!cloud.user||!cloud.box||cloud.busy||cloud.blocked)return;if(cloud.conflict){cloudStatus('conflict');return}if(!navigator.onLine){cloudStatus('offline');return}cloud.busy=true;const owner=cloud.user.id;cloudStatus('syncing');try{
  const remote=await fetchRemote();if(cloud.user?.id!==owner||cloud.blocked)return;
  // A previous request may have committed even if its response was lost.
  if(remote&&remote.mutation_id===cloud.box.mutation){cloud.box.revision=remote.revision;cloud.box.dirty=false;cloud.box.lastSync=remote.updated_at;storeBox()}
  const version=remote?.revision||0;
  if(cloud.box.dirty&&version!==cloud.box.revision){cloud.conflict=remote||{payload:blankAccount(),revision:0,updated_at:null};cloudStatus('conflict');return}
  if(!cloud.box.dirty){if(remote&&version!==cloud.box.revision){if(document.querySelector('.modal')||document.activeElement?.matches('input,textarea,select')){cloudStatus('ready');return}cloud.box={...freshBox(),state:remote.payload,revision:version,lastSync:remote.updated_at};if(!storeBox())return;applyBox()}else if(!remote&&cloud.box.revision>0){cloudStatus('error');return}cloudStatus(remote?'synced':'ready');setTimeout(()=>syncCoachRelational(),0);return}
  const snapshot=clone(cloud.box);const {data,error}=await cloud.client.rpc('save_coach_notebook',{expected_revision:snapshot.revision,notebook:snapshot.state,request_id:snapshot.mutation});if(error)throw error;if(cloud.user?.id!==owner||cloud.blocked)return;
  if(!data?.ok){const latest=await fetchRemote();if(cloud.user?.id!==owner||cloud.blocked)return;cloud.conflict=latest||{payload:blankAccount(),revision:0,updated_at:null};cloudStatus('conflict');return}
  cloud.box.revision=data.revision;cloud.box.lastSync=data.updated_at;if(cloud.box.mutation===snapshot.mutation)cloud.box.dirty=false;const saved=storeBox();cloudStatus(!saved?'storage':cloud.box.dirty?'pending':'synced');if(cloud.box.dirty)scheduleSync();else setTimeout(()=>syncCoachRelational(),0);
}catch{if(cloud.user?.id===owner)cloudStatus(navigator.onLine?'error':'offline')}finally{cloud.busy=false}}
function downloadSnapshot(value,label){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=`muscu-coach-${label}-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function conflictModal(){if(!cloud.conflict)return;const describe=s=>`${s.history.length} séances · ${s.tests.length} repères · ${s.draft?'séance en cours':'aucune séance en cours'}`;showModal('Deux appareils, deux versions.',`<p class="small muted">Aucune version n’a été écrasée. Exporte les deux copies avant de choisir celle qui deviendra ton carnet commun.</p><div class="conflict-version"><b>Sur cet appareil</b><p class="small muted">${describe(state)}</p><button class="btn btn-outline" data-cloud="exportLocal">Exporter cette copie</button></div><div class="conflict-version"><b>En ligne</b><p class="small muted">${describe(cloud.conflict.payload)}</p><button class="btn btn-outline" data-cloud="exportRemote">Exporter cette copie</button></div>`,[{label:'Garder celle de cet appareil',fn:()=>resolveConflict('local')},{label:'Utiliser celle en ligne',kind:'outline',fn:()=>resolveConflict('remote')}]);}
function resolveConflict(choice){confirmDialog('Confirmer cette version ?', 'L’autre version sera conservée dans une archive locale. Exporte-la aussi si tu veux la garder après un nettoyage du navigateur.',()=>{if(!cloud.conflict)return;try{localStorage.setItem(accountKey(cloud.user.id)+':archive:'+Date.now(),JSON.stringify({local:state,remote:cloud.conflict.payload}))}catch{toast('Archive impossible. Exporte les deux copies avant de libérer de la place.');return}const remote=cloud.conflict;cloud.conflict=null;if(choice==='remote'){cloud.box={...freshBox(),state:remote.payload,revision:remote.revision,lastSync:remote.updated_at};storeBox();applyBox();scheduleSync()}else{cloud.box.revision=remote.revision;save()}},'Utiliser cette version');}
function migrateGuest(){if(!cloud.user)return;let guest;try{const raw=localStorage.getItem(KEY)||localStorage.getItem('muscu-coach-v2');if(!raw){toast('Aucun ancien carnet sur ce navigateur. Utilise Importer si tu as un fichier.');return}guest=normalise(JSON.parse(raw))}catch{toast('Ancien carnet illisible. Utilise une copie exportée.');return}confirmDialog('Transférer ton ancien carnet ?',`${guest.history.length} séances et ${guest.tests.length} repères remplaceront le carnet de ce compte. L’original local sera conservé. Exporte le carnet du compte avant de continuer s’il contient déjà des séances.`,()=>{state=guest;save();render();toast('Carnet transféré localement. Vérifie le statut de synchronisation.');},'Transférer vers mon compte')}
function authModal(){location.assign('/connexion.html')}
async function logout(){if(cloud.busy){toast('Attends la fin de la synchronisation.');return}if(cloud.box?.dirty||cloud.conflict){toast('Synchronise ou résous le conflit avant de te déconnecter. Tu peux aussi exporter ton carnet.');return}const owner=cloud.user?.id;const {error}=await cloud.client.auth.signOut({scope:'local'});if(error){toast('Déconnexion impossible. Réessaie avec du réseau.');return}attachSession(null);sessionStorage.removeItem('coach-guest');location.replace('/accueil.html');if(owner)localStorage.removeItem(accountKey(owner));toast('Déconnecté. Le carnet du compte reste en ligne.');}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-cloud]');if(!b)return;const cmd=b.dataset.cloud;if(['login','signup','reset','password'].includes(cmd))authModal(cmd);else if(cmd==='account')navigate('settings');else if(cmd==='sync'){if(cloud.conflict)conflictModal();else{cloud.coachingSynced=false;syncCloud();setTimeout(()=>syncCoachRelational(true),1200)}}else if(cmd==='logout')logout();else if(cmd==='migrate')migrateGuest();else if(cmd==='exportLocal')downloadSnapshot(state,'appareil');else if(cmd==='exportRemote'&&cloud.conflict)downloadSnapshot(cloud.conflict.payload,'en-ligne');});
window.addEventListener('online',async()=>{if(!cloud.client)return;const {data,error}=await cloud.client.auth.getSession();if(error){cloudStatus('error');return}attachSession(data.session);cloud.coachingSynced=false;syncCloud();setTimeout(()=>syncCoachRelational(true),1200)});window.addEventListener('offline',()=>{cloud.coachingSynced=false;if(cloud.user)cloudStatus('offline')});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncCloud()});
window.addEventListener('storage',ev=>{if(cloud.user&&ev.key===accountKey(cloud.user.id)){shield('Carnet ouvert dans un autre onglet.','Recharge cette page pour reprendre la dernière copie enregistrée.',true)}});
async function initCloud(){{try{const last=JSON.parse(localStorage.getItem(LAST_ACCOUNT)||'null');if(last&&localStorage.getItem(accountKey(last.id)))attachSession({user:last})}catch{}}const cfg=window.COACH_CONFIG||{};if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){render();return}try{cloud.client=window.SupabaseSDK.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,flowType:'pkce'},global:{fetch:(url,options={})=>fetch(url,{...options,signal:options.signal||AbortSignal.timeout(15000)})}});cloud.client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(!session&&!navigator.onLine)return;attachSession(session);},0)});cloudStatus('connecting');const {data,error}=await cloud.client.auth.getSession();if(error)throw error;if(data.session||navigator.onLine)attachSession(data.session);if(!data.session&&!cloud.user)cloudStatus('local');render();}catch{cloudStatus('error');render()}}
const initializeAccount=initCloud;
initCloud=async function(){const cfg=window.COACH_CONFIG||{};if(cfg.supabaseUrl&&cfg.supabasePublishableKey)shield('Retrouver ton carnet.', 'Vérification du compte et de la copie sur cet appareil…');try{await initializeAccount()}finally{if(!cloud.cacheError){let guest=false;try{if(new URL(location.href).searchParams.get('mode')==='local')sessionStorage.setItem('coach-guest','1');guest=sessionStorage.getItem('coach-guest')==='1'}catch{}if(!cloud.user&&!guest){location.replace('/accueil.html');return}document.body.classList.remove('entry-check');unshield()}}};
window.MuscuCoachCloudAPI=Object.freeze({isSignedIn:()=>!!cloud.user?.id,getUserId:()=>cloud.user?.id||null,isRelationalReady:()=>!!(cloud.user?.id&&cloud.client&&window.MuscuCoachStorage?.isRemoteBound()),syncCoaching:()=>syncCoachRelational(true)});
// Only one editable tab avoids two local writers replacing a pending envelope.
async function bootCloud(){if(navigator.locks){navigator.locks.request('muscu-coach-editor',{ifAvailable:true},async lock=>{if(!lock){shield('Déjà ouvert dans un autre onglet.','Ferme l’autre onglet Muscu Coach puis recharge celui-ci.',true);return}await initCloud();await new Promise(()=>{});}).catch(()=>shield('Ouverture interrompue.','Recharge l’app pour reprendre.',true))}else await initCloud();}
setInterval(()=>{if(document.visibilityState==='visible')syncCloud()},30000);
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('/sw.js').catch(()=>{});
bootCloud();
